### ISSUE TITLE
[Meta Issue] General cleanup

### ISSUE THREAD

**Issue by bugabinga** [isp-insoft-gmbh/SwingX#3]
The code is quite old and crufty.
Herr is a list of steps that lead to improved code base:

- [ ] Remove redundancies and unnecessary files and comments. (e.g. `LICENSE` and `COPYING` or 90% commented out `checkstyle.xml`) #5 
- [x] Update `pom.xml` with new metadata (developers, CI, docs, etc) #6 
- [ ] Update dependencies or remove them #7
- [ ] Use some public CI Service (Travis?) #8
- [ ] Update to Java 12+ #9
- [ ] Refactor to use modules #10
- [ ] Apply ISP formatter and code guidelines to source code (fix warnings) #11
- [ ] Remove overlapping APIs with new `java.desktop` module #12

~To start working on these points, create an issue with the __same title__ and reference _this_ one.~ DONE.

**Comment by Bios-Marcel** [comment]
Why is the `LICENSE` unnecessary? Or did you mean to remove `COPYING` file and leave `LICENSE`?

**Comment by bugabinga** [comment]
> 
> 
> Why is the `LICENSE` unnecessary? Or did you mean to remove `COPYING` file and leave `LICENSE`?

Yes, remove one and leave the other. No matter which one.
